apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: quarkus241205 
  janus-idp.io/tekton: quarkus241205
  backstage.io/kubernetes-id: quarkus241205
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: quarkus241205
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  