apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: quarkus241205
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: quarkus241205 
  name: quarkus241205
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: quarkus241205 
